create table User_Table (uuid Integer generated by default as identity(start with 1000, increment by 1) primary key, fname varchar(32) not null, lname varchar(32) not null, mname varchar(32), age Integer not null, gender varchar(1) not null, phone varchar(10) not null,zip Integer);
Insert into User_Table (fname,lname,age,gender,phone,zip) values('George','Hobert',39,'M','8372929101',93839);
Insert into User_Table (fname,lname,age,gender,phone,zip) values('Lambert','Francis',24,'M','9876543210',35254);
Insert into User_Table (fname,lname,age,gender,phone,zip) values('Yue','Alexandria',31,'F','6547893218',87452);
Insert into User_Table (fname,lname,age,gender,phone,zip) values('Sam','Hoffman',46,'F','7531946825',15935);
